<?php

/**
 * This is the model base class for the table "{{mail_subscribe}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MailSubscribe".
 *
 * Columns in table "{{mail_subscribe}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $list
 * @property string $email
 * @property string $hashcode
 *
 */
abstract class BaseMailSubscribe extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{mail_subscribe}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MailSubscribe|MailSubscribes', $n);
	}

	public static function representingColumn() {
		return 'list';
	}

	public function rules() {
		return array(
			array('list, email, hashcode', 'required'),
			array('list', 'length', 'max'=>32),
			array('email', 'length', 'max'=>255),
			array('hashcode', 'length', 'max'=>127),
			array('id, list, email, hashcode', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'list' => Yii::t('app', 'List'),
			'email' => Yii::t('app', 'Email'),
			'hashcode' => Yii::t('app', 'Hashcode'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('list', $this->list, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('hashcode', $this->hashcode, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}